#import <Foundation/Foundation.h>
#import "TWInlineResponse200.h"
#import "TWCategory.h"
#import "TWInlineResponse2002.h"
#import "TWInlineResponse2001.h"
#import "TWApi.h"

/**
* tweak-api
* Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface TWCategoryApi: NSObject <TWApi>

extern NSString* kTWCategoryApiErrorDomain;
extern NSInteger kTWCategoryApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Count instances of the model matched by where from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) categoryCountWithWhere: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Create a new instance of the model and persist it into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryCreateWithData: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) categoryCreateChangeStreamGetCategoriesChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) categoryCreateChangeStreamPostCategoriesChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Delete a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return NSObject*
-(NSNumber*) categoryDeleteByIdWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) categoryExistsGetCategoriesidExistsWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) categoryExistsHeadCategoriesidWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Find all instances of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWCategory>*
-(NSNumber*) categoryFindWithFilter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWCategory>* output, NSError* error)) handler;


/// Find a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// @param filter Filter defining fields and include (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryFindByIdWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Find first instance of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryFindOneWithFilter: (NSString*) filter
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Counts children of Category.
/// 
///
/// @param _id Category id
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) categoryPrototypeCountChildrenWithId: (NSString*) _id
    where: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Creates a new instance in children of this model.
/// 
///
/// @param _id Category id
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeCreateChildrenWithId: (NSString*) _id
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Deletes all children of this model.
/// 
///
/// @param _id Category id
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) categoryPrototypeDeleteChildrenWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete a related item by id for children.
/// 
///
/// @param _id Category id
/// @param fk Foreign key for children
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) categoryPrototypeDestroyByIdChildrenWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(NSError* error)) handler;


/// Find a related item by id for children.
/// 
///
/// @param _id Category id
/// @param fk Foreign key for children
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeFindByIdChildrenWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Queries children of Category.
/// 
///
/// @param _id Category id
/// @param filter  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWCategory>*
-(NSNumber*) categoryPrototypeGetChildrenWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWCategory>* output, NSError* error)) handler;


/// Fetches belongsTo relation parent.
/// 
///
/// @param _id Category id
/// @param refresh  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeGetParentWithId: (NSString*) _id
    refresh: (NSNumber*) refresh
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Category id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeUpdateAttributesPatchCategoriesidWithId: (NSString*) _id
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Category id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeUpdateAttributesPutCategoriesidWithId: (NSString*) _id
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Update a related item by id for children.
/// 
///
/// @param _id Category id
/// @param fk Foreign key for children
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryPrototypeUpdateByIdChildrenWithId: (NSString*) _id
    fk: (NSString*) fk
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Replace attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Model id
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryReplaceByIdWithId: (NSString*) _id
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Replace an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryReplaceOrCreateWithData: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Update instances of the model matched by {{where}} from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2001*
-(NSNumber*) categoryUpdateAllWithWhere: (NSString*) where
    data: (TWCategory*) data
    completionHandler: (void (^)(TWInlineResponse2001* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryUpsertPatchCategoriesWithData: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryUpsertPutCategoriesWithData: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;


/// Update an existing model instance or insert a new one into the data source based on the where criteria.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCategory*
-(NSNumber*) categoryUpsertWithWhereWithWhere: (NSString*) where
    data: (TWCategory*) data
    completionHandler: (void (^)(TWCategory* output, NSError* error)) handler;



@end
