#import <Foundation/Foundation.h>
#import "TWInlineResponse200.h"
#import "TWCustomer.h"
#import "TWInlineResponse2002.h"
#import "TWAccessToken.h"
#import "TWDesign.h"
#import "TWInlineResponse2001.h"
#import "TWApi.h"

/**
* tweak-api
* Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface TWCustomerApi: NSObject <TWApi>

extern NSString* kTWCustomerApiErrorDomain;
extern NSInteger kTWCustomerApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Confirm a user registration with email verification token.
/// 
///
/// @param uid 
/// @param token 
/// @param redirect  (optional)
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerConfirmWithUid: (NSString*) uid
    token: (NSString*) token
    redirect: (NSString*) redirect
    completionHandler: (void (^)(NSError* error)) handler;


/// Count instances of the model matched by where from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) customerCountWithWhere: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Create a new instance of the model and persist it into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerCreateWithData: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) customerCreateChangeStreamGetCustomersChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) customerCreateChangeStreamPostCustomersChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Delete a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return NSObject*
-(NSNumber*) customerDeleteByIdWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) customerExistsGetCustomersidExistsWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) customerExistsHeadCustomersidWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Find all instances of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWCustomer>*
-(NSNumber*) customerFindWithFilter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWCustomer>* output, NSError* error)) handler;


/// Find a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// @param filter Filter defining fields and include (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerFindByIdWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Find first instance of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerFindOneWithFilter: (NSString*) filter
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Login a user with username/email and password.
/// 
///
/// @param credentials 
/// @param include Related objects to include in the response. See the description of return value for more details. (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSObject*
-(NSNumber*) customerLoginWithCredentials: (NSObject*) credentials
    include: (NSString*) include
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Logout a user with access token.
/// 
///
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerLogoutWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Counts accessTokens of Customer.
/// 
///
/// @param _id Customer id
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) customerPrototypeCountAccessTokensWithId: (NSString*) _id
    where: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Counts designs of Customer.
/// 
///
/// @param _id Customer id
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) customerPrototypeCountDesignsWithId: (NSString*) _id
    where: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Creates a new instance in accessTokens of this model.
/// 
///
/// @param _id Customer id
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWAccessToken*
-(NSNumber*) customerPrototypeCreateAccessTokensWithId: (NSString*) _id
    data: (TWAccessToken*) data
    completionHandler: (void (^)(TWAccessToken* output, NSError* error)) handler;


/// Creates a new instance in designs of this model.
/// 
///
/// @param _id Customer id
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWDesign*
-(NSNumber*) customerPrototypeCreateDesignsWithId: (NSString*) _id
    data: (TWDesign*) data
    completionHandler: (void (^)(TWDesign* output, NSError* error)) handler;


/// Deletes all accessTokens of this model.
/// 
///
/// @param _id Customer id
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerPrototypeDeleteAccessTokensWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Deletes all designs of this model.
/// 
///
/// @param _id Customer id
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerPrototypeDeleteDesignsWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete a related item by id for accessTokens.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for accessTokens
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerPrototypeDestroyByIdAccessTokensWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete a related item by id for designs.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for designs
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerPrototypeDestroyByIdDesignsWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(NSError* error)) handler;


/// Find a related item by id for accessTokens.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for accessTokens
/// 
///  code:200 message:"Request was successful"
///
/// @return TWAccessToken*
-(NSNumber*) customerPrototypeFindByIdAccessTokensWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(TWAccessToken* output, NSError* error)) handler;


/// Find a related item by id for designs.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for designs
/// 
///  code:200 message:"Request was successful"
///
/// @return TWDesign*
-(NSNumber*) customerPrototypeFindByIdDesignsWithId: (NSString*) _id
    fk: (NSString*) fk
    completionHandler: (void (^)(TWDesign* output, NSError* error)) handler;


/// Queries accessTokens of Customer.
/// 
///
/// @param _id Customer id
/// @param filter  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWAccessToken>*
-(NSNumber*) customerPrototypeGetAccessTokensWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWAccessToken>* output, NSError* error)) handler;


/// Queries designs of Customer.
/// 
///
/// @param _id Customer id
/// @param filter  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWDesign>*
-(NSNumber*) customerPrototypeGetDesignsWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWDesign>* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Customer id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerPrototypeUpdateAttributesPatchCustomersidWithId: (NSString*) _id
    data: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Customer id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerPrototypeUpdateAttributesPutCustomersidWithId: (NSString*) _id
    data: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Update a related item by id for accessTokens.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for accessTokens
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWAccessToken*
-(NSNumber*) customerPrototypeUpdateByIdAccessTokensWithId: (NSString*) _id
    fk: (NSString*) fk
    data: (TWAccessToken*) data
    completionHandler: (void (^)(TWAccessToken* output, NSError* error)) handler;


/// Update a related item by id for designs.
/// 
///
/// @param _id Customer id
/// @param fk Foreign key for designs
/// @param data  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWDesign*
-(NSNumber*) customerPrototypeUpdateByIdDesignsWithId: (NSString*) _id
    fk: (NSString*) fk
    data: (TWDesign*) data
    completionHandler: (void (^)(TWDesign* output, NSError* error)) handler;


/// Replace attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Model id
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerReplaceByIdWithId: (NSString*) _id
    data: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Replace an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerReplaceOrCreateWithData: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Reset password for a user with email.
/// 
///
/// @param options 
/// 
///  code:204 message:"Request was successful"
///
/// @return 
-(NSNumber*) customerResetPasswordWithOptions: (NSObject*) options
    completionHandler: (void (^)(NSError* error)) handler;


/// Update instances of the model matched by {{where}} from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2001*
-(NSNumber*) customerUpdateAllWithWhere: (NSString*) where
    data: (TWCustomer*) data
    completionHandler: (void (^)(TWInlineResponse2001* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerUpsertPatchCustomersWithData: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerUpsertPutCustomersWithData: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;


/// Update an existing model instance or insert a new one into the data source based on the where criteria.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWCustomer*
-(NSNumber*) customerUpsertWithWhereWithWhere: (NSString*) where
    data: (TWCustomer*) data
    completionHandler: (void (^)(TWCustomer* output, NSError* error)) handler;



@end
