#import <Foundation/Foundation.h>
#import "TWInlineResponse200.h"
#import "TWTag.h"
#import "TWInlineResponse2002.h"
#import "TWInlineResponse2001.h"
#import "TWApi.h"

/**
* tweak-api
* Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface TWTagApi: NSObject <TWApi>

extern NSString* kTWTagApiErrorDomain;
extern NSInteger kTWTagApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Count instances of the model matched by where from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse200*
-(NSNumber*) tagCountWithWhere: (NSString*) where
    completionHandler: (void (^)(TWInlineResponse200* output, NSError* error)) handler;


/// Create a new instance of the model and persist it into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagCreateWithData: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) tagCreateChangeStreamGetTagsChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Create a change stream.
/// 
///
/// @param options  (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSURL*
-(NSNumber*) tagCreateChangeStreamPostTagsChangeStreamWithOptions: (NSString*) options
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Delete a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return NSObject*
-(NSNumber*) tagDeleteByIdWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) tagExistsGetTagsidExistsWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Check whether a model instance exists in the data source.
/// 
///
/// @param _id Model id
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2002*
-(NSNumber*) tagExistsHeadTagsidWithId: (NSString*) _id
    completionHandler: (void (^)(TWInlineResponse2002* output, NSError* error)) handler;


/// Find all instances of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return NSArray<TWTag>*
-(NSNumber*) tagFindWithFilter: (NSString*) filter
    completionHandler: (void (^)(NSArray<TWTag>* output, NSError* error)) handler;


/// Find a model instance by {{id}} from the data source.
/// 
///
/// @param _id Model id
/// @param filter Filter defining fields and include (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagFindByIdWithId: (NSString*) _id
    filter: (NSString*) filter
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Find first instance of the model matched by filter from the data source.
/// 
///
/// @param filter Filter defining fields, where, include, order, offset, and limit (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagFindOneWithFilter: (NSString*) filter
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Tag id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagPrototypeUpdateAttributesPatchTagsidWithId: (NSString*) _id
    data: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Patch attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Tag id
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagPrototypeUpdateAttributesPutTagsidWithId: (NSString*) _id
    data: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Replace attributes for a model instance and persist it into the data source.
/// 
///
/// @param _id Model id
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagReplaceByIdWithId: (NSString*) _id
    data: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Replace an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagReplaceOrCreateWithData: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Update instances of the model matched by {{where}} from the data source.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWInlineResponse2001*
-(NSNumber*) tagUpdateAllWithWhere: (NSString*) where
    data: (TWTag*) data
    completionHandler: (void (^)(TWInlineResponse2001* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagUpsertPatchTagsWithData: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Patch an existing model instance or insert a new one into the data source.
/// 
///
/// @param data Model instance data (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagUpsertPutTagsWithData: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;


/// Update an existing model instance or insert a new one into the data source based on the where criteria.
/// 
///
/// @param where Criteria to match model instances (optional)
/// @param data An object of model property name/value pairs (optional)
/// 
///  code:200 message:"Request was successful"
///
/// @return TWTag*
-(NSNumber*) tagUpsertWithWhereWithWhere: (NSString*) where
    data: (TWTag*) data
    completionHandler: (void (^)(TWTag* output, NSError* error)) handler;



@end
